# https://taskfile.dev/usage/

# task JMENO

version: '3'

tasks:
  brun:
    dir: backend
    cmds:
      - arelo -p '**/*.go' -p '**/.env' -i '**/*_test.go' -- go run .
  
  bbuild:
    dir: backend
    cmds:
      - sed -i 's\127.0.0.1:44871\:44871\g' main.go  # zmenim url
      - GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" .
      - sed -i 's\:44871\127.0.0.1:44871\g' main.go  # zmenim zpět

  frun:
    dir: frontend
    cmds:
      - npm run dev
  
  fbuild:
    dir: frontend
    cmds:
      - sed -i 's\http://localhost:44871/api\/api\g' src/main.ts
      - npm run build
      - sed -i 's\/api\http://localhost:44871/api\g' src/main.ts
  
  tunel:
    cmds:
      - ssh -L 5432:localhost:5432 filip.ruzicka@svs.gyarab.cz